// User unauthorized
export const UNAUTHORIZED = 'UNAUTHORIZED';
// Authorization Token Not Found.
export const AUTHORIZATION_TOKEN_NOT_FOUND = 'AUTHORIZATION_TOKEN_NOT_FOUND';
export const AUTHORIZATION_TOKEN_CREATE_USER_WHERE_ALLOW_ONE =
  'AUTHORIZATION_TOKEN_CREATE_USER_WHERE_ALLOW_ONE';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_LOGIN_FIELD_EXISTED = 'USER_LOGIN_FIELD_EXISTED';
export const USER_PHONE_FIELD_EXISTED = 'USER_PHONE_FIELD_EXISTED';
export const USER_EMAIL_FIELD_EXISTED = 'USER_EMAIL_FIELD_EXISTED';
export const USER_NOT_SET_PHONE = 'USER_NOT_SET_PHONE';

// security code validate error
export const SECURITY_COMPARE_FAILED = 'SECURITY_COMPARE_FAILED';
